---
- name: check rbenv installed
  shell: source ~/.bash_profile; which rbenv
  register: rbenv_installed
  ignore_errors: yes

- block:
  - name: install rbenv and ruby-build
    git:
      repo: '{{ item.repo }}'
      dest: '{{ item.dest }}'
    with_items:
      - repo: https://github.com/sstephenson/rbenv.git
        dest: ~/.rbenv
      - repo: https://github.com/sstephenson/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build
      - repo: https://github.com/rkh/rbenv-update.git
        dest: ~/.rbenv/plugins/ruby-update

  - name: settup rbenv
    shell: '{{ item.cmd }}'
    with_items:
      - cmd: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
      - cmd: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
      - cmd: source ~/.bash_profile; rbenv -v
  when: rbenv_installed.rc == 1

- block:
  - name: check ruby installed
    shell: source ~/.bash_profile; rbenv versions | grep {{ ruby_version }}
    register: ruby_installed
    ignore_errors: yes

  - name: install ruby
    shell: '{{ item.cmd }}'
    with_items:
      - cmd: source ~/.bash_profile; rbenv install '{{ ruby_version }}'
      - cmd: source ~/.bash_profile; rbenv global '{{ ruby_version }}'
      - cmd: source ~/.bash_profile; gem install bundler
    when: ruby_installed.rc == 1

